apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: apps
spec:
  project: default
  source:
    repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
    targetRevision: HEAD
    path: off
  destination:
    name: in-cluster
    namespace: argocd
  revisionHistoryLimit: 2