apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
    targetRevision: HEAD
    path: off/
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  revisionHistoryLimit: 3