apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: management
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.4.6
    chart: aws-load-balancer-controller
    helm:
      values: |
        clusterName: gitops
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  revisionHistoryLimit: 3
