apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: management
    server: https://kubernetes.default.svc
  project: management
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.9.1
    chart: crossplane
    helm:
      values: |
        provider:
          packages:
            - xpkg.upbound.io/crossplane-contrib/provider-aws:v0.34.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
