apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: crossplane-vpc
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 10.10.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags:
      - key: Name
        value: crossplane-vpc
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: crossplane-ig
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: crossplane-vpc
    tags:
      - key: Name
        value: crossplane-ig
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-subnet1
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 10.10.1.0/24
    vpcIdRef:
      name: crossplane-vpc
    mapPublicIPOnLaunch: true
    tags:
      - key: Name
        value: crossplane-subnet1
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-subnet2
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1c
    cidrBlock: 10.10.2.0/24
    vpcIdRef:
      name: crossplane-vpc
    mapPublicIPOnLaunch: true
    tags:
      - key: Name
        value: crossplane-subnet2
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: crossplane-routetable
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: crossplane-ig
    associations:
      - subnetIdRef:
          name: crossplane-subnet1
    vpcIdRef:
      name: crossplane-vpc
    tags:
      - key: Name
        value: crossplane-routetable
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: web-traffic-sg
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: crossplane-vpc
    groupName: web-traffic-sg
    description: Allow Web Traffic Access
    egress:
      # AWS will treat it as all ports any protocol
      - ipProtocol: '-1'
        ipRanges:
          - cidrIp: 0.0.0.0/0
    # ingress:
    #   - fromPort: 5432
    #     ipProtocol: tcp
    #     ipRanges:
    #       - cidrIp: 10.0.0.0/8
    #     toPort: 5432
    tags:
      - key: Name
        value: crossplane-web-traffic-sg
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: http-sg-rule
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    protocol: "tcp"
    fromPort: 80
    toPort: 80
    type: "ingress"
    securityGroupIdRef:
      name: web-traffic-sg
    cidrBlock: "0.0.0.0/0"
    description: "HTTP"
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: https-sg-rule
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    protocol: "tcp"
    fromPort: 443
    toPort: 443
    type: "ingress"
    securityGroupIdRef:
      name: web-traffic-sg
    cidrBlock: "0.0.0.0/0"
    description: "HTTPS"
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-ec2-instance
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    imageId: ami-0b0dcb5067f052a63
    instanceType: t3a.medium
    securityGroupRefs:
      - name: web-traffic-sg
    subnetIdRef:
      name: crossplane-subnet1
    tags:
      - key: Name
        value: crossplane-ec2-instance
    userData: "IyEgL2Jpbi9iYXNoCnN1ZG8gYXB0LWdldCB1cGRhdGUKc3VkbyBhcHQtZ2V0IGluc3RhbGwgLXkgYXBhY2hlMgpzdWRvIHN5c3RlbWN0bCBzdGFydCBhcGFjaGUyCnN1ZG8gc3lzdGVtY3RsIGVuYWJsZSBhcGFjaGUyCmVjaG8gIlRoZSBwYWdlIHdhcyBjcmVhdGVkIGJ5IHRoZSB1c2VyIGRhdGEiIHwgc3VkbyB0ZWUgL3Zhci93d3cvaHRtbC9pbmRleC5odG1s"
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws