apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-managed-instance
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    imageId: ami-0b0dcb5067f052a63
    instanceType: t2.medium
    instanceMarketOptions:
      marketType: spot
      spotOptions:
        instanceInterruptionBehavior: terminate
        spotInstanceType: persistent
    tags:
      - key: Name
        value: crossplane-managed-instance
  providerConfigRef:
    name: aws-provider
  providerRef:
    name: provider-aws