kind: Namespace
apiVersion: v1
metadata:
  name: external-dns
  labels:
    name: external-dns
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: management
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.12.1
    chart: external-dns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  revisionHistoryLimit: 3
