kind: Namespace
apiVersion: v1
metadata:
  name: karpenter
  labels:
    name: karpenter
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: management
  source:
    repoURL: https://charts.karpenter.sh
    targetRevision: "0.16.3"
    chart: karpenter
    helm:
      values: |
        serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn: arn:aws:iam::113067560560:role/gitops-cluster-20221215023816941900000003
        clusterName: gitops
        clusterEndpoint: https://F6D2A46D5DBC749D4EAD6DCF50296C99.sk1.us-east-1.eks.amazonaws.com
        aws:
          defaultInstanceProfile: KarpenterNodeInstanceProfile-gitops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  revisionHistoryLimit: 3
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      Name: "*private*"
    securityGroupSelector:
      karpenter.sh/discovery/gitops: gitops
    tags:
      karpenter.sh/discovery/gitops: gitops
  ttlSecondsAfterEmpty: 30