apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      revision: HEAD
      directories:
      - path: 99-monitoring/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: monitoring
      source:
        repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: monitoring