apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 8.5.1
    chart: logstash
    helm:
      values: |
        antiAffinity: "soft"
        logstashPipeline:
          logstash.conf: |
            input {
              beats {
                port => 5044
              }
            }
            output {
              elasticsearch {
                hosts => "https://elasticsearch-master:9200"
              }
            }
        envFrom:
          - secretRef:
              name: elasticsearch-master-credentials
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  revisionHistoryLimit: 3