apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.8.7
    chart: loki-stack
    helm:
      values: |
        loki:
          enabled: true
        promtail:
          enabled: true
        fluent-bit:
          enabled: false
        grafana:
          enabled: true
          grafana.ini:
            users:
              viewers_can_edit: true
            auth:
              disable_login_form: true
              disable_signout_menu: true
            auth.anonymous:
              enabled: true
              org_role: Admin
        prometheus:
          enabled: true
        filebeat:
          enabled: false
        logstash:
          enabled: false
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
