apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
    targetRevision: 3.8.3
    chart: metrics-server
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true
  revisionHistoryLimit: 3