# -- Deploy Argo CD Applications within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications:
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
        - values.yaml
        - ../argocd-install-values-override.yaml
      path: 02-gitops/argocd/argocd-install/argo-cd
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
        - values.yaml
        - ../argocd-apps-values-override.yaml
      path: 02-gitops/argocd/argocd-install/argocd-apps
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        allowEmpty: true
        selfHeal: true
  - name: argocd-appprojects
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: 02-gitops/argocd/argocd-appprojects
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        allowEmpty: true
        selfHeal: true
  - name: management
    namespace: argocd
    destination:
      namespace: management
      server: https://kubernetes.default.svc
    project: management
    source:
      path: 02-gitops/argocd/argocd-apps
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        allowEmpty: true
        selfHeal: true
  - name: monitoring
    namespace: argocd
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: monitoring
    source:
      path: 99-monitoring/k8s-helm
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: true
        allowEmpty: true
        selfHeal: true

# -- Deploy Argo CD Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
projects:
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false


# -- Deploy Argo CD ApplicationSets within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
applicationsets:
- name: apps-ecommerce
  namespace: argocd
  additionalLabels: {}
  additionalAnnotations: {}
  # See PR #10026 (ArgoCD v2.5 or later)
  # goTemplate: false
  generators:
  - git:
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      revision: HEAD
      directories:
        - path: 03-applications/ecommerce/
  template:
    metadata:
      name: '{{path.basename}}'
      labels: {}
      annotations: {}
    spec:
      project: ecommerce
      source:
        repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: true
          jsonnet: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
  syncPolicy:
    # Set Application finalizer
    preserveResourcesOnDeletion: false
- name: apps-wordpress
  namespace: argocd
  additionalLabels: {}
  additionalAnnotations: {}
  # See PR #10026 (ArgoCD v2.5 or later)
  # goTemplate: false
  generators:
  - git:
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      revision: HEAD
      directories:
        - path: 03-applications/wordpress/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels: {}
      annotations: {}
    spec:
      project: marketing
      source:
        repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
  syncPolicy:
    # Set Application finalizer
    preserveResourcesOnDeletion: false
- name: apps-monitoring
  namespace: argocd
  additionalLabels: {}
  additionalAnnotations: {}
  # See PR #10026 (ArgoCD v2.5 or later)
  # goTemplate: false
  generators:
  - git:
      repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
      revision: HEAD
      directories:
        - path: 99-monitoring/k8s-manifests/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels: {}
      annotations: {}
    spec:
      project: monitoring
      source:
        repoURL: https://github.com/rickardosmith/gitops_with_argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
  syncPolicy:
    # Set Application finalizer
    preserveResourcesOnDeletion: false